#!/usr/bin/env python3
"""Build the session-notes handover manifest (PP-14).

Handover version lives in the filename (`{project}_session-notes_v{N}_{YYYYMMDD}T{HHMM}Z.md`), so
every prompt has to re-derive "latest" by globbing and parsing `{N}` numerically (a plain sort puts
v9 after v13) and guarding against strays. This builds a manifest so a reader can look "latest" up
instead of re-deriving it.

The manifest is `session-notes/manifest.json` — an index of every handover, from which the latest
per project is the highest-`version` entry. The root support repository tracks the paired handover
files but deliberately ignores this generated manifest, so it is rebuilt by scanning and never
hand-edited.

`write-handover` runs this after writing a new handover. Readers (`resume-session`,
`derive-worklist`, `loop-worklist`) prefer the manifest and fall back to the glob rule if absent.

Pair integrity (P-09): every handover is a Markdown/HTML *pair*. A Markdown handover without its
HTML companion is a contract violation, so both modes below exit non-zero while listing each
unpaired file. The build mode still writes the manifest first (recording `"html": null`), so the
index stays truthful while the violation is being repaired. Handover freshness against a project's
default head is deliberately NOT checked here — freshness is advisory and belongs to
`workspace_preflight.py` warnings.

Usage (from the portfolio-prompts/ directory):
    python tools/build-handover-manifest.py           # (re)write session-notes/manifest.json
    python tools/build-handover-manifest.py --check     # exit 1 if missing/stale or a pair is incomplete

No third-party dependencies.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent          # portfolio-prompts/
SESSION_NOTES = HERE.parent / "session-notes"          # test-automation-portfolio/session-notes/
MANIFEST = SESSION_NOTES / "manifest.json"

NAME_RE = re.compile(
    r"^(?P<project>.+)_session-notes_v(?P<version>\d+)_(?P<ts>\d{8}T\d{4}Z)\.md$"
)


def iso(ts: str) -> str:
    # 20260707T0716Z -> 2026-07-07T07:16:00Z
    return f"{ts[0:4]}-{ts[4:6]}-{ts[6:8]}T{ts[9:11]}:{ts[11:13]}:00Z"


def unpaired(session_notes: Path = None) -> list[str]:
    """Markdown handovers whose HTML companion is missing (P-09 pair-integrity violations)."""
    folder = SESSION_NOTES if session_notes is None else session_notes
    missing: list[str] = []
    if folder.is_dir():
        for md in sorted(folder.glob("*_session-notes_v*.md")):
            if NAME_RE.match(md.name) and not md.with_suffix(".html").exists():
                missing.append(md.name)
    return missing


def build(session_notes: Path = None) -> dict:
    folder = SESSION_NOTES if session_notes is None else session_notes
    handovers = []
    if folder.is_dir():
        for md in sorted(folder.glob("*_session-notes_v*.md")):
            m = NAME_RE.match(md.name)
            if not m:
                continue
            handovers.append(
                {
                    "project": m["project"],
                    "version": int(m["version"]),
                    "created": iso(m["ts"]),
                    "file": md.name,
                    "html": md.with_suffix(".html").name
                    if md.with_suffix(".html").exists()
                    else None,
                }
            )
    handovers.sort(key=lambda h: (h["project"], h["version"]))
    latest = {}
    for h in handovers:
        cur = latest.get(h["project"])
        if cur is None or h["version"] > cur["version"]:
            latest[h["project"]] = {"version": h["version"], "file": h["file"]}
    return {
        "note": "Generated by portfolio-prompts/tools/build-handover-manifest.py — do not hand-edit.",
        "handovers": handovers,
        "latest": latest,
    }


def dumps(manifest: dict) -> str:
    return json.dumps(manifest, indent=2, ensure_ascii=True) + "\n"


def report_unpaired(missing: list[str]) -> None:
    print(f"build-handover-manifest: PAIR INTEGRITY FAIL — {len(missing)} Markdown handover(s) "
          "have no HTML companion (P-09):")
    for name in missing:
        print(f"  - {name}")


def main() -> int:
    check = "--check" in sys.argv[1:]
    manifest = build()
    text = dumps(manifest)
    missing = unpaired()
    if check:
        if not MANIFEST.exists():
            print("build-handover-manifest: manifest.json is MISSING — run the builder.")
            return 1
        current = MANIFEST.read_text(encoding="utf-8")
        # Compare on the handover index only (ignore the volatile nothing here — both are derived).
        if current != text:
            print("build-handover-manifest: manifest.json is STALE — run the builder.")
            return 1
        if missing:
            report_unpaired(missing)
            return 1
        print("build-handover-manifest: manifest.json is up to date; all handover pairs complete.")
        return 0
    if not SESSION_NOTES.is_dir():
        print(f"build-handover-manifest: no session-notes/ at {SESSION_NOTES} — nothing to do.")
        return 0
    MANIFEST.write_text(text, encoding="utf-8", newline="\n")
    n = len(manifest["handovers"])
    print(f"build-handover-manifest: wrote {MANIFEST.relative_to(HERE.parent)} ({n} handovers, "
          f"{len(manifest['latest'])} projects).")
    if missing:
        report_unpaired(missing)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
